// Code generated by jtd-codegen for Java + Jackson v0.2.1

package org.vcell.optimization.jtd;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class Vcellopt {
    @JsonProperty("dataSet")
    private List<List<Double>> dataSet;

    @JsonProperty("optProblem")
    private OptProblem optProblem;

    @JsonProperty("optResultSet")
    private OptResultSet optResultSet;

    @JsonProperty("status")
    private VcelloptStatus status;

    @JsonProperty("statusMessage")
    private String statusMessage;

    public Vcellopt() {
    }

    /**
     * Getter for dataSet.<p>
     */
    public List<List<Double>> getDataSet() {
        return dataSet;
    }

    /**
     * Setter for dataSet.<p>
     */
    public void setDataSet(List<List<Double>> dataSet) {
        this.dataSet = dataSet;
    }

    /**
     * Getter for optProblem.<p>
     */
    public OptProblem getOptProblem() {
        return optProblem;
    }

    /**
     * Setter for optProblem.<p>
     */
    public void setOptProblem(OptProblem optProblem) {
        this.optProblem = optProblem;
    }

    /**
     * Getter for optResultSet.<p>
     */
    public OptResultSet getOptResultSet() {
        return optResultSet;
    }

    /**
     * Setter for optResultSet.<p>
     */
    public void setOptResultSet(OptResultSet optResultSet) {
        this.optResultSet = optResultSet;
    }

    /**
     * Getter for status.<p>
     */
    public VcelloptStatus getStatus() {
        return status;
    }

    /**
     * Setter for status.<p>
     */
    public void setStatus(VcelloptStatus status) {
        this.status = status;
    }

    /**
     * Getter for statusMessage.<p>
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Setter for statusMessage.<p>
     */
    public void setStatusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
    }
}
