name: Nightly BioModel DataBase CLI Test
on:
  schedule: 
    - cron: "0 7 * * *"
  workflow_dispatch:

env:
  python-version: "3.9"
  poetry-version: "1.2.1"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Our Code
        uses: actions/checkout@v3
        with: 
          ref: '${{ github.ref }}'
          
      - name: Get GH Reference
        run: echo '${{ github.ref }}' >> ~/github.ref
        
      - name: Upload Ref
        uses: actions/upload-artifact@v3
        with:
          name: github_hash
          path: ~/github.ref

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          
      - name: Install poetry
        run: python3 -m pip install poetry==${{ env.poetry-version }}
        
      - name: Install other python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: build vcell-cli-utils package
        run: |
          cd vcell-cli-utils
          poetry install
      
      - name: build vcell-admin package
        run: |
          cd docker/swarm/vcell-admin
          poetry install
          
      - name: build vcell-opt package
        run: |
          cd pythonProject/vcell-opt
          poetry install
      
      - name: Setup Java for Build
        uses: actions/setup-java@v2
        with: 
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Build VCell Jars
        run: mvn clean install dependency:copy-dependencies
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Export
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=/tmp/image.tar
          build-args: | # Max ram for Ubuntu GitHub workflow is 7GB (as of 12/9/22), using MB for precision (0.8 of 7gb)
            MAX_JAVA_MEM=5734
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar
      
      # Report a Problem to Slack
      - name: Report Problem to Slack
        if: ${{ failure() }}
        run: curl -X POST -F token="${{ secrets.SLACK_BOT_TOKEN }}" -F channel=${{ secrets.SLACK_CHANNEL_VCELL_DEV_TOKEN }} -F text="Uh-Oh! The *Build Step* of Nightly Testing Action on GitHub Failed ( ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} )! This may need attention..." https://slack.com/api/chat.postMessage

      # Tmate just in case
      - name: Setup tmate session 3
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        
  execute:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Create Docker Image Dir
        run: mkdir /tmp/docker
        
      - name: Download Docker Image from `build` Job
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker

      - name: Load Downloaded Docker Image
        run: docker load --input /tmp/docker/$(ls /tmp/docker)
        
        # Get files from BMDB
      - name: Checkout Input Files
        uses: actions/checkout@v3
        with: 
          repository: sys-bio/temp-biomodels
        
        # Do the execution
      - name: Begin Execution
        #$(docker image ls | grep "<none>" | awk '{print $3;}')  to get image id
        run: docker run -v $GITHUB_WORKSPACE/omex_files:/root $(docker image ls | grep "<none>" | awk '{print $3;}') execute -i "/root" -o "/root/output" # grabs image and runs
  
      - name: Check For Failure
        run: |
          errorSearch=$(find ${GITHUB_WORKSPACE}/omex_files -name detailedErrorLog.txt)
          if [ $(find ${GITHUB_WORKSPACE}/omex_files -name detailedErrorLog.txt | wc -l) -gt 0 ]
          then 
            errorMessage="Errors were enocuntered, see the following error files:\n $errorSearch"
            curl -X POST -F token="${{ secrets.SLACK_BOT_TOKEN }}" -F channel=${{ secrets.SLACK_CHANNEL_VCELL_DEV_TOKEN }} -F text=${errorMessage} https://slack.com/api/chat.postMessage
            exit 10
          fi
      
      - name: Report Results to Slack
        run: curl -X POST -F token="${{ secrets.SLACK_BOT_TOKEN }}" -F channel=${{ secrets.SLACK_CHANNEL_VCELL_DEV_TOKEN }} -F text="It appears all models have succeeded from BMDB!" https://slack.com/api/chat.postMessage    

      # Report a Problem to Slack
      - name: Report Problem to Slack
        if: ${{ failure() }}
        run: curl -X POST -F token="${{ secrets.SLACK_BOT_TOKEN }}" -F channel=${{ secrets.SLACK_CHANNEL_VCELL_DEV_TOKEN }} -F text="Oops! The *Execute Step* of Nightly Testing Action on GitHub Failed ( ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ). Go see what happened!" https://slack.com/api/chat.postMessage

      - name: Setup tmate session 3
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
 
